In [2]:
import pandas as pd

from pandas_cleaning_data import new_columns_names

In [4]:
ndata = pd.read_csv("netflix1.csv")

In [5]:
ndata

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"
...,...,...,...,...,...,...,...,...,...,...
8785,s8797,TV Show,Yunus Emre,Not Given,Turkey,1/17/2017,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas"
8786,s8798,TV Show,Zak Storm,Not Given,United States,9/13/2018,2016,TV-Y7,3 Seasons,Kids' TV
8787,s8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,12/15/2016,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,s8784,TV Show,Yoko,Not Given,Pakistan,6/23/2018,2016,TV-Y,1 Season,Kids' TV
8789,s8786,TV Show,YOM,Not Given,Pakistan,6/7/2018,2016,TV-Y7,1 Season,Kids' TV

In [6]:
ndata.columns

Index(['show_id', 'type', 'title', 'director', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in'],
      dtype='object')

In [8]:
ndata.drop(columns = "director")

,show_id,type,title,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"
...,...,...,...,...,...,...,...,...,...
8785,s8797,TV Show,Yunus Emre,Turkey,1/17/2017,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas"
8786,s8798,TV Show,Zak Storm,United States,9/13/2018,2016,TV-Y7,3 Seasons,Kids' TV
8787,s8801,TV Show,Zindagi Gulzar Hai,Pakistan,12/15/2016,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,s8784,TV Show,Yoko,Pakistan,6/23/2018,2016,TV-Y,1 Season,Kids' TV
8789,s8786,TV Show,YOM,Pakistan,6/7/2018,2016,TV-Y7,1 Season,Kids' TV

In [9]:
ndata = ndata.drop(columns= "director")

In [10]:
ndata

,show_id,type,title,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"
...,...,...,...,...,...,...,...,...,...
8785,s8797,TV Show,Yunus Emre,Turkey,1/17/2017,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas"
8786,s8798,TV Show,Zak Storm,United States,9/13/2018,2016,TV-Y7,3 Seasons,Kids' TV
8787,s8801,TV Show,Zindagi Gulzar Hai,Pakistan,12/15/2016,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,s8784,TV Show,Yoko,Pakistan,6/23/2018,2016,TV-Y,1 Season,Kids' TV
8789,s8786,TV Show,YOM,Pakistan,6/7/2018,2016,TV-Y7,1 Season,Kids' TV

In [11]:
ndata.columns

Index(['show_id', 'type', 'title', 'country', 'date_added', 'release_year',
       'rating', 'duration', 'listed_in'],
      dtype='object')

In [12]:
new_columns_names = []
for i in ndata.columns:
    new_columns_names.append(i.capitalize())

In [13]:
new_columns_names

['Show_id',
 'Type',
 'Title',
 'Country',
 'Date_added',
 'Release_year',
 'Rating',
 'Duration',
 'Listed_in']

In [14]:
ndata.columns = new_columns_names

In [15]:
ndata

,Show_id,Type,Title,Country,Date_added,Release_year,Rating,Duration,Listed_in
0,s1,Movie,Dick Johnson Is Dead,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"
...,...,...,...,...,...,...,...,...,...
8785,s8797,TV Show,Yunus Emre,Turkey,1/17/2017,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas"
8786,s8798,TV Show,Zak Storm,United States,9/13/2018,2016,TV-Y7,3 Seasons,Kids' TV
8787,s8801,TV Show,Zindagi Gulzar Hai,Pakistan,12/15/2016,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,s8784,TV Show,Yoko,Pakistan,6/23/2018,2016,TV-Y,1 Season,Kids' TV
8789,s8786,TV Show,YOM,Pakistan,6/7/2018,2016,TV-Y7,1 Season,Kids' TV

In [16]:
ndata.duplicated().sum()

np.int64(0)

In [17]:
# we do not have duplicates in our data but lit it be
ndata.drop_duplicates(inplace = True)

In [18]:
ndata.duplicated().sum()

np.int64(0)

In [19]:
ndata.isna()

,Show_id,Type,Title,Country,Date_added,Release_year,Rating,Duration,Listed_in
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
8785,False,False,False,False,False,False,False,False,False
8786,False,False,False,False,False,False,False,False,False
8787,False,False,False,False,False,False,False,False,False
8788,False,False,False,False,False,False,False,False,False
8789,False,False,False,False,False,False,False,False,False

In [20]:
ndata.isna().sum()

Show_id         0
Type            0
Title           0
Country         0
Date_added      0
Release_year    0
Rating          0
Duration        0
Listed_in       0
dtype: int64

In [ ]:
# we have no values that are null but if we had
#ndata.dropna(inplace=True)

In [22]:
ndata["Show_id"].unique()

array(['s1', 's3', 's6', ..., 's8801', 's8784', 's8786'],
      shape=(8790,), dtype=object)

In [21]:
ndata["Show_id"].apply(lambda x: x.split("s")[1])

0          1
1          3
2          6
3         14
4          8
        ...
8785    8797
8786    8798
8787    8801
8788    8784
8789    8786
Name: Show_id, Length: 8790, dtype: object

In [23]:
ndata["Show_id"] = ndata["Show_id"].apply(lambda x: x.split("s")[1])

In [24]:
ndata

,Show_id,Type,Title,Country,Date_added,Release_year,Rating,Duration,Listed_in
0,1,Movie,Dick Johnson Is Dead,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,3,TV Show,Ganglands,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,6,TV Show,Midnight Mass,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,14,Movie,Confessions of an Invisible Girl,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,8,Movie,Sankofa,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"
...,...,...,...,...,...,...,...,...,...
8785,8797,TV Show,Yunus Emre,Turkey,1/17/2017,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas"
8786,8798,TV Show,Zak Storm,United States,9/13/2018,2016,TV-Y7,3 Seasons,Kids' TV
8787,8801,TV Show,Zindagi Gulzar Hai,Pakistan,12/15/2016,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,8784,TV Show,Yoko,Pakistan,6/23/2018,2016,TV-Y,1 Season,Kids' TV
8789,8786,TV Show,YOM,Pakistan,6/7/2018,2016,TV-Y7,1 Season,Kids' TV

In [29]:
ndata["Show_id"][2]

np.int64(6)

In [30]:
type(ndata["Show_id"][4])

numpy.int64

In [28]:
ndata["Show_id"] = ndata["Show_id"].astype(int)

In [32]:
ndata["Date_added"] = ndata["Date_added"].apply(lambda x: x.replace("/", "-"))

In [34]:
ndata

,Show_id,Type,Title,Country,Date_added,Release_year,Rating,Duration,Listed_in
0,1,Movie,Dick Johnson Is Dead,United States,9-25-2021,2020,PG-13,90 min,Documentaries
1,3,TV Show,Ganglands,France,9-24-2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,6,TV Show,Midnight Mass,United States,9-24-2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,14,Movie,Confessions of an Invisible Girl,Brazil,9-22-2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,8,Movie,Sankofa,United States,9-24-2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"
...,...,...,...,...,...,...,...,...,...
8785,8797,TV Show,Yunus Emre,Turkey,1-17-2017,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas"
8786,8798,TV Show,Zak Storm,United States,9-13-2018,2016,TV-Y7,3 Seasons,Kids' TV
8787,8801,TV Show,Zindagi Gulzar Hai,Pakistan,12-15-2016,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,8784,TV Show,Yoko,Pakistan,6-23-2018,2016,TV-Y,1 Season,Kids' TV
8789,8786,TV Show,YOM,Pakistan,6-7-2018,2016,TV-Y7,1 Season,Kids' TV

In [35]:
ndata["Country"].value_counts()

Country
United States     3240
India             1057
United Kingdom     638
Pakistan           421
Not Given          287
                  ...
Luxembourg           1
Senegal              1
Belarus              1
Puerto Rico          1
Cyprus               1
Name: count, Length: 86, dtype: int64

In [37]:
df = ndata["Country"].value_counts().reset_index()
df[df["Country"] == "United Kingdom"]

          Country  count
2  United Kingdom    638

In [38]:
df

           Country  count
0    United States   3240
1            India   1057
2   United Kingdom    638
3         Pakistan    421
4        Not Given    287
..             ...    ...
81      Luxembourg      1
82         Senegal      1
83         Belarus      1
84     Puerto Rico      1
85          Cyprus      1

[86 rows x 2 columns]

In [39]:
(ndata["Country"] == "United Kingdom").sum()

np.int64(638)

In [41]:
ndata["Country"].value_counts()["Bulgaria"]

np.int64(5)

In [42]:
(ndata["Country"] == "United Kingdom").sum()

np.int64(638)

In [43]:
ndata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Show_id       8790 non-null   int64
 1   Type          8790 non-null   object
 2   Title         8790 non-null   object
 3   Country       8790 non-null   object
 4   Date_added    8790 non-null   object
 5   Release_year  8790 non-null   int64
 6   Rating        8790 non-null   object
 7   Duration      8790 non-null   object
 8   Listed_in     8790 non-null   object
dtypes: int64(2), object(7)
memory usage: 618.2+ KB

In [44]:
#How many Movies vs TV Shows
ndata["Type"].value_counts()

Type
Movie      6126
TV Show    2664
Name: count, dtype: int64

In [47]:
ndata["Country"].value_counts().head(10)

Country
United States     3240
India             1057
United Kingdom     638
Pakistan           421
Not Given          287
Canada             271
Japan              259
South Korea        214
France             213
Spain              182
Name: count, dtype: int64

In [56]:
ndata.groupby('Release_year').size().sort_values()

Release_year
2018    1146
2017    1030
2019    1030
2020     953
2016     901
        ...
1925       1
1947       1
1959       1
1966       1
1961       1
Length: 74, dtype: int64

In [55]:
ndata['Listed_in'].value_counts().head(10)

Listed_in
Dramas, International Movies                        362
Documentaries                                       359
Stand-Up Comedy                                     334
Comedies, Dramas, International Movies              274
Dramas, Independent Movies, International Movies    252
Kids' TV                                            219
Children & Family Movies                            215
Children & Family Movies, Comedies                  201
Documentaries, International Movies                 186
Dramas, International Movies, Romantic Movies       180
Name: count, dtype: int64

In [58]:
pd.crosstab(ndata['Country'], ndata['Type']).sort_values('Movie', ascending=False)

Type            Movie  TV Show
Country
United States    2395      845
India             976       81
United Kingdom    387      251
Not Given         257       30
Canada            187       84
...               ...      ...
Jordan              0        2
Luxembourg          0        1
Puerto Rico         0        1
Senegal             0        1
Ukraine             0        2

[86 rows x 2 columns]

In [ ]:
# import pandas as pd
# from pandas_cleaning_data import new_columns_names
# ndata = pd.read_csv("netflix1.csv")
# ndata
# ndata.columns
# ndata.drop(columns = "director")
# ndata = ndata.drop(columns= "director")
# ndata
# ndata.columns
# new_columns_names = []
# for i in ndata.columns:
#     new_columns_names.append(i.capitalize())
# new_columns_names
# ndata.columns = new_columns_names
# ndata
# ndata.duplicated().sum()
# ndata.drop_duplicates(inplace = True)
# ndata.duplicated().sum()
# ndata.isna()
# ndata.isna().sum()
# ndata["Show_id"].unique()
# ndata["Show_id"].apply(lambda x: x.split("s")[1])
# ndata["Show_id"] = ndata["Show_id"].apply(lambda x: x.split("s")[1])
# ndata
# ndata["Show_id"][2]
# type(ndata["Show_id"][4])
# ndata["Show_id"] = ndata["Show_id"].astype(int)
# ndata["Date_added"] = ndata["Date_added"].apply(lambda x: x.replace("/", "-"))
# ndata
# ndata["Country"].value_counts()
# df = ndata["Country"].value_counts().reset_index()
# df[df["Country"] == "United Kingdom"]
# df
# (ndata["Country"] == "United Kingdom").sum()
# ndata["Country"].value_counts()["Bulgaria"]
# (ndata["Country"] == "United Kingdom").sum()
# ndata.info()
# ndata["Type"].value_counts()
# ndata["Country"].value_counts().head(10)
# ndata.groupby('Release_year').size().sort_values()
# ndata['Listed_in'].value_counts().head(10)
# pd.crosstab(ndata['Country'], ndata['Type']).sort_values('Movie', ascending=False)